#!/usr/bin/env bash

pandoc -s $opts -t beamer $1 -o "./pdfs/$(basename $1 .md).pdf" \
	-V title="Client Server" \
  -V subtitle="My presentation subtitle" \
	-V author="Mhmd Ali Hsen" \
	-V institute="Al Afaq" \
	-V theme="Madrid" \
	-V colortheme="wolverine" \
	-V fonttheme="structurebold" \
  -V lang="en-US" \
	-V fontsize="9pt" \
	-V aspectratio="169" \
	-V date="2023"
